### ISSUE TITLE
Error executing get for (key : )io.camunda.operate.dto.ProcessDefinition

### ISSUE THREAD

**Issue by AmruthaMotamarry** [camunda-community-hub/camunda-operate-client-java#5] opened 2022-10-28 10:53 UTC
@berndruecker  Facing the issue when operate helm chart has spring jwt token environment variables.

io.camunda.operate.exception.OperateException: Error executing get for (key : )io.camunda.operate.dto.ProcessDefinition

**Comment by chDame** [comment] 2022-10-28 11:35
Hi @AmruthaMotamarry,

Could you share the full stacktrace? As you have a 401 with tasklist, could you verify that you provided the right permissions in identity ?

**Comment by AmruthaMotamarry** [comment] 2022-10-28 11:39
Hi @chDame, thanks for the quick reply.

Please find the stack trace of operate exception

io.camunda.operate.exception.OperateException: Error executing get for (key : 1)io.camunda.operate.dto.ProcessDefinition
	at io.camunda.operate.CamundaOperateClient.get(CamundaOperateClient.java:162)
	at io.camunda.operate.CamundaOperateClient.getProcessDefinition(CamundaOperateClient.java:49)
	at com.optum.camundaclient.util.OperateUtilImpl.getProcessDefinition(OperateUtilImpl.java:57)
	at com.optum.camundaclient.controller.OperateController.getProcessDefinition(OperateController.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1071)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:964)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.23.1</center>
</body>
</html>
"; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2391)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:735)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:659)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:2005)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:802)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4784)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4690)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3652)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3620)
	at io.camunda.operate.util.JsonUtils.toResult(JsonUtils.java:44)
	at io.camunda.operate.CamundaOperateClient.get(CamundaOperateClient.java:160)
	... 53 more

**Comment by chDame** [comment] 2022-10-28 11:53
OK, it's the same error that you're getting with tasklist. You have an unauthorized request and keycloak is redirecting you to the login page when you're requesting something. Then the Json parser is failing because it receives an html body rather than a json response.
For the simplicity, we will track these problem from the tasklist perspective.

**Comment by AmruthaMotamarry** [comment] 2022-10-28 11:55
Sure, Thank you

**Comment by chDame** [comment] 2022-10-28 12:53
Hi @AmruthaMotamarry,

Since the error is resolved in tasklist, I would suggest the same procedure here. First step will be to reproduce with postman (or equivalent) :
execute a POST to **${yourkeycloakUrl}**/auth/realms/camunda-platform/protocol/openid-connect/token
with params ( x-www-form-urlencoded): grant_type=client_credentials&client_id=**${clientId}**&client_secret=**${clientSecret}**

retrieve the access_token from the response and then execute a query against your tasklist GET **${operate}**/v1/process-definitions/3
with the authentication header : Authorization : Bearer **${access_token}**

And I would suggest that you verify you've actually provided the Operate API permissions to your client in identity ;)

**Comment by AmruthaMotamarry** [comment] 2022-10-28 13:08
Hi @chDame ,

Thanks for the suggestions. 

1. Verified the permissions for operate API
2. Reproduced with postman

Facing 404 issue

**Comment by chDame** [comment] 2022-10-28 13:09
can you reach operate from your browser ? Are you using the same URL ?

**Comment by AmruthaMotamarry** [comment] 2022-10-31 03:53
Hi @chDame,

sorry for the delay. Yes we are using same url and can reach from browser.

For standalone request to operate from postman, we are getting the below as response
{
    "status": 404,
    "message": "No process definition found for key 1 ",
    "instance": "d98c5e4b-c4d2-4f66-b185-974c435c92e1",
    "type": "Requested resource not found"
}
Is this the reason for the issue "Error executing get for (key : 1)io.camunda.operate.dto.ProcessDefinition" because earlier if there is no process definition available we used to get null as response.

**Comment by chDame** [comment] 2022-10-31 07:36
Hi @AmruthaMotamarry

Could you share the operarate url you're providing to the client? It should be something like http://${operateServer}:${operatePort} or http://${someDns}

The 404 you get from operate with Postman looks nice : The process definition doesn't exist.
The 404 you got with the client is an HTML page and means it tries to reach an endpoint that doesn't exist. And it shouldn't happen. 

Alos what is your camunda version ?

**Comment by AmruthaMotamarry** [comment] 2022-10-31 08:53
Hi @chDame,

Please find the operate url with dns : https://camunda-8-dev.orxcoreplatform.optum.com/operate

Camunda version : 8.1.2

**Comment by chDame** [comment] 2022-10-31 08:55
Ok, I've released a new version 1.3.2 that should display some more information in case of error. Could you try it and share the stack trace again ?

**Comment by chDame** [comment] 2022-10-31 08:58
And I guess I undestood your error. You're passing an empty key. This is the reason for the error message Error executing get for (key : )io.camunda.operate.dto.ProcessDefinition

You should pass the key. I'll improve the client to send an error if the key is empty.

**Comment by chDame** [comment] 2022-10-31 09:20
Hi @AmruthaMotamarry,

I've just released a new version 1.3.3 that should handle some errors more nicely. Could you try it and tell me what is the stack trace you get ?

**Comment by AmruthaMotamarry** [comment] 2022-10-31 11:08
Hi @chDame,

I have upgraded operate dependency to version 1.3.3 . Please find the error stack below

io.camunda.operate.exception.OperateException: Error executing get for (key : 1)io.camunda.operate.dto.ProcessDefinition on https://camunda-8-dev.orxcoreplatform.optum.com/v1/process-definitions/1
	at io.camunda.operate.CamundaOperateClient.get(CamundaOperateClient.java:169)
	at io.camunda.operate.CamundaOperateClient.getProcessDefinition(CamundaOperateClient.java:49)
	at com.optum.camundaclient.util.OperateUtilImpl.getProcessDefinition(OperateUtilImpl.java:57)
	at com.optum.camundaclient.controller.OperateController.getProcessDefinition(OperateController.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1071)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:964)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.23.1</center>
</body>
</html>
"; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2391)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:735)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:659)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:2005)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:802)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4784)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4690)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3652)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3620)
	at io.camunda.operate.util.JsonUtils.toResult(JsonUtils.java:44)
	at io.camunda.operate.CamundaOperateClient.get(CamundaOperateClient.java:167)
	... 53 more

**Comment by chDame** [comment] 2022-10-31 11:22
Hi @AmruthaMotamarry,

In the logs, it seems that you're not providing the good URL to the client.
You provided https://camunda-8-dev.orxcoreplatform.optum.com
And should have provided https://camunda-8-dev.orxcoreplatform.optum.com/operate

As a result, the target URL is:
https://camunda-8-dev.orxcoreplatform.optum.com/v1/process-definitions/1
and it should be https://camunda-8-dev.orxcoreplatform.optum.com/operate/v1/process-definitions/1

**Comment by AmruthaMotamarry** [comment] 2022-10-31 11:44
Hi @chDame 

Thanks for the version upgrade. Errors are more clear now and the issue is resolved. Thanks again for your support and you can go ahead with closing this.

**Comment by chDame** [comment] 2022-10-31 15:35
Great

**Closed by chDame** 2022-10-31 15:35 UTC
